package com.nanda.portfolio.controller;
import com.nanda.portfolio.dto.PortfolioDtos.*; import com.nanda.portfolio.service.PortfolioContentService; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/admin") public class AdminPortfolioApiController {
 private final PortfolioContentService service; public AdminPortfolioApiController(PortfolioContentService s){service=s;}
 @GetMapping("/profile") Object profile(){return service.profile();} @PutMapping("/profile") Object profile(@Valid @RequestBody ProfileData d){return service.saveProfile(d);}
 @GetMapping("/skills") Object skills(){return service.skills();} @PostMapping("/skills") @ResponseStatus(HttpStatus.CREATED) Object addSkill(@Valid @RequestBody SkillData d){return service.saveSkill(null,d);} @PutMapping("/skills/{id}") Object skill(@PathVariable long id,@Valid @RequestBody SkillData d){return service.saveSkill(id,d);} @DeleteMapping("/skills/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delSkill(@PathVariable long id){service.deleteSkill(id);}
 @GetMapping("/projects") Object projects(){return service.adminProjects();} @PostMapping("/projects") @ResponseStatus(HttpStatus.CREATED) Object addProject(@Valid @RequestBody ProjectData d){return service.saveProject(null,d);} @GetMapping("/projects/{id}") Object project(@PathVariable long id){return service.project(id);} @PutMapping("/projects/{id}") Object project(@PathVariable long id,@Valid @RequestBody ProjectData d){return service.saveProject(id,d);} @DeleteMapping("/projects/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delProject(@PathVariable long id){service.deleteProject(id);}
 @PostMapping("/projects/{id}/technologies") @ResponseStatus(HttpStatus.CREATED) Object technology(@PathVariable long id,@Valid @RequestBody TechnologyData d){return service.addTechnology(id,d);} @DeleteMapping("/projects/{projectId}/technologies/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delTech(@PathVariable long projectId,@PathVariable long id){service.deleteTechnology(projectId,id);}
 @PostMapping("/projects/{id}/media") @ResponseStatus(HttpStatus.CREATED) Object media(@PathVariable long id,@Valid @RequestBody MediaData d){return service.saveMedia(id,null,d);} @PutMapping("/projects/{projectId}/media/{id}") Object media(@PathVariable long projectId,@PathVariable long id,@Valid @RequestBody MediaData d){return service.saveMedia(projectId,id,d);} @DeleteMapping("/projects/{projectId}/media/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delMedia(@PathVariable long projectId,@PathVariable long id){service.deleteMedia(projectId,id);}
 @GetMapping("/contact") Object contact(){return service.contact();} @PutMapping("/contact") Object contact(@RequestBody ContactData d){return service.saveContact(d);}
}
