import {AnimatePresence,motion} from 'framer-motion'; import {profile,projects,skillGroups,experience,education,achievements} from '../../data/portfolio'; import {useApp} from '../../store'; import {ContactForm} from './ContactForm';
const t={duration:.55,ease:[.22,1,.36,1] as const};
export function SectionOverlay(){const {section,setSection,setProject}=useApp();return <main className={`overlay ${section==='home'?'is-home':'is-content'}`}><AnimatePresence mode="wait"><motion.section key={section} className="copy" initial={{opacity:0,x:-28}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}} transition={t}>
{section==='home'&&<><p className="hello">HELLO, I'M</p><h1>MOHAN</h1><div className="role">AI ENGINEER<br/>FULL STACK DEVELOPER</div><p className="intro">I build intelligent applications, scalable systems and useful digital experiences.</p><div className="hero-actions"><button onClick={()=>setSection('projects')}>VIEW MY WORK</button><button onClick={()=>setSection('about')}>ABOUT ME →</button></div></>}
{section==='about'&&<><p className="eyebrow">ABOUT MOHAN</p><h2>Curious mind.<br/>Practical builder.</h2><p className="body">{profile.intro}</p><div className="mini-grid"><article><b>FOCUS</b><span>AI · BACKEND · AUTOMATION</span></article><article><b>LOCATION</b><span>{profile.location}</span></article></div><button className="orange" onClick={()=>setSection('skills')}>EXPLORE SKILLS →</button></>}
{section==='projects'&&<><p className="eyebrow">SELECTED WORK</p><h2>Projects with<br/>real-world purpose.</h2><div className="project-list">{projects.map((p,i)=><button key={p.title} onClick={()=>setProject(i)}><span style={{background:p.accent}}>{i+1}</span><b>{p.title}</b><em>VIEW ↗</em></button>)}</div></>}
{section==='skills'&&<><p className="eyebrow">MY TOOLKIT</p><h2>Technologies I<br/>build with.</h2><div className="skill-grid">{skillGroups.map(g=><article key={g.name}><b>{g.name}</b><span>{g.items.join(' · ')}</span></article>)}</div></>}
{section==='experience'&&<><p className="eyebrow">EXPERIENCE</p><h2>Learning through<br/>shipping.</h2>{experience.map(x=><article className="paper" key={x.role}><small>{x.dates}</small><h3>{x.role}</h3><b>{x.organization}</b><p>{x.description}</p></article>)}</>}
{section==='education'&&<><p className="eyebrow">EDUCATION</p><h2>Strong foundations.</h2><article className="paper"><small>{education.graduation}</small><h3>{education.degree}</h3><b>{education.branch}</b><p>{education.college}</p></article></>}
{section==='achievements'&&<><p className="eyebrow">MILESTONES</p><h2>Always moving<br/>forward.</h2><div className="notes">{achievements.map((a,i)=><article key={a} className={`note n${i}`}>{a}</article>)}</div></>}
{section==='contact'&&<><p className="eyebrow">SAY HELLO</p><h2>Let's make something<br/>great together.</h2><ContactForm/></>}
</motion.section></AnimatePresence>{section!=='home'&&<button className="back" onClick={()=>setSection('home')}>← BACK HOME</button>}</main>}
